server:
  port: ${PORT:8889}
  servlet:
    context-path: /pet-shop

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  datasource:
#    driver-class-name: org.postgresql.Driver
    url: ${$JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/pet_shop}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:123}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          user_jdbc_metadata_defaults: false
        ddl-auto: validate
