server:
  port: 8889
  servlet:
    context-path: /pet-shop

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pet_shop
    username: postgres
    password: 123

  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          user_jdbc_metadata_defaults: false
        ddl-auto: validate
